# Builder
FROM node:24-alpine AS builder

ARG VITE_API_URL
ARG VITE_APP_NAME

RUN apk add --no-cache git

WORKDIR /app

RUN git clone https://github.com/aku-upan/linkup-studio.git .

RUN npm install
RUN npm run build

# Production

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]